### ISSUE TITLE
Initialize PVC for Persistent Airflow Logs

### ISSUE THREAD

**Issue by LiamF-FS** [bcgov/NR-BCWAT#38]
#### Rationale

One of the benefits of Airflow is to see the status of jobs ran in a hosted dashboard.

To get the full benefits of this, we require a PVC initialized where the worker pods deposit their logs.

#### Solution

For OKD, initializing an NFS server and storageClass with access should suffice. We then can create the PVC within our `/charts/airflow/values.okd.yaml`.

```
logs:
  persistence:
    enabled: true
    # https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/log-persistence.md
    # Accessmode Defaults to "ReadWriteMany"
    # Requires Config of:
    # - Persistent Volume
    # - Persistent Volume Claim
    # - Storage Class
    # Look into https://github.com/kubernetes-csi/csi-driver-nfs/tree/master/charts/latest:
    # This will initialize an NFS Server in which our Persistent Volumes will be created
    # Can automatically create a storageClass, assign as default, and PVC will use that storage class
    # Automatically creates a Persistent Volume on Disk when PVC created
```

For BCGov Openshift, we will need to discuss requesting a PV.

For OKD, this will require setting up a Network File System.
